### ISSUE TITLE
AttributeError: fn

### ISSUE THREAD

**Issue by tristan-k** [dglent/vcf2addressbook#1]
I'm using [vdirsyncer](https://github.com/pimutils/vdirsyncer) to generate a singlefile vcf from my owncloud carddav server. Trying to import the vcf file with your script results in an error. Any suggestions?

```
$ python --version                       
Python 2.7.12
$ python vcf2addressbook.py contacts.vcf 
Traceback (most recent call last):
  File "vcf2addressbook.py", line 219, in <module>
    out = Vcf2addressbook(ff)
  File "vcf2addressbook.py", line 48, in __init__
    self.add_vcf()
  File "vcf2addressbook.py", line 86, in add_vcf
    fn = vcard.fn.value.encode('utf-8')
  File "/usr/lib/python2.7/dist-packages/vobject/base.py", line 477, in __getattr__
    raise exceptions.AttributeError, name
AttributeError: fn
```

**Comment by dglent** [comment]
Hello,

Can you test the above fix ?

**Comment by tristan-k** [comment]
Different error.

```
python vcf2addressbook.py contacts.vcf                                                                          
Traceback (most recent call last):
  File "vcf2addressbook.py", line 222, in <module>
    out = Vcf2addressbook(ff)
  File "vcf2addressbook.py", line 48, in __init__
    self.add_vcf()
  File "vcf2addressbook.py", line 92, in add_vcf
    attributs = p.params.get("TYPE", [])
  File "/usr/lib/python2.7/dist-packages/vobject/base.py", line 477, in __getattr__
    raise exceptions.AttributeError, name
AttributeError: params
```

**Comment by dglent** [comment]
The data should have this format and this script treats vcf files of version 3.0

BEGIN:VCARD
VERSION:3.0
FN:The full name
N:Mr Last name;First name;;;
EMAIL;TYPE=INTERNET:01@net.com
TEL;TYPE=CELL:00000000000000
TEL;TYPE=WORK:+000000000000
END:VCARD

Which format has your file ?

**Comment by tristan-k** [comment]
The file was originally created on an android device running [davdroid](https://github.com/bitfireAT/davdroid) and was then synced to ownclouds carddav interface.

Here is an excerpt:

```
BEGIN:VADDRESSBOOK
BEGIN:VCARD
VERSION:3.0
UID:3e979c64-17b8-4c96-8e04-72367e3ec777
PRODID:+//IDN bitfire.at//DAVdroid/0.9.1.3 vcard4android ez-vcard/0.9.8
FN: Name Surename
N:Name;Surename;;;
EMAIL;TYPE=x-internet;PREF=1:name.surename@email.net
REV:2016-01-19T13:44:50+00:00
END:VCARD
```

**Comment by dglent** [comment]
Could you try to remove the first line 
BEGIN:VADDRESSBOOK
and the last line
END:VADDRESSBOOK
?
